### ISSUE TITLE
apply for random sample result of devset and testset

### ISSUE THREAD

**Issue by haerbinwyzhaha** [zhangsheng93/cMedQA#4]
您好，在您的文章里提到对于devset、testset，对于每个query，都会随机的抽取答案池中来做为待排序集，从而用Top1的结果来判断正确与否，但是公开的数据集中没有这样的poolset，能否提供下当时随机sample的结果，从而方便做下对比实验呢。

**Comment by zhangsheng93** [comment]
dev set 和 test set 中第四列标记为0的即为负样本，是从答案池中随机抽的，组成了100个样本池。
